### ISSUE TITLE
Hello, thank you for your contribution,The error code was reported in the update at 19:00 on June 16th, is it my problem or the code problem?

### ISSUE THREAD

**Issue by shumoLR** [MokkaBoss1/ComfyUI-Mokkaboss1#3]
Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.3\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Mokkaboss1\__init__.py", line 13, in <module>
    from ComfyUI_Mokkaboss1.nodes.LandscapeBackgrounds import LandscapeBackgrounds
  File "F:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Mokkaboss1\nodes\LandscapeBackgrounds.py", line 169
    ]
    ^
SyntaxError: unmatched ']'

**Comment by MokkaBoss1** [comment]
Hi that is my error Sorry. Will correct as soon as I can.
